### ISSUE TITLE
about  get required .dat.json files

### ISSUE THREAD

**Issue by vagrant-soul** [HeartofPhos/exile-leveling#10]
Can you release these files together with the source code? I'm a beginner and can't get these files myself. I use Chinese and I am trying to translate these files

**Comment by HeartofPhos** [comment]
I've done an export using https://github.com/HeartofPhos/exile-export, I added the Traditional Chinese exports as well since I assume you will be interested in them.
[exports.zip](https://github.com/HeartofPhos/exile-leveling/files/9331571/exports.zip)

You can seed the data by copying the appropriate files here
![image](https://user-images.githubusercontent.com/43216176/184498386-ee70c2da-9d8b-4c42-9410-40bfe5b7e4d3.png)
and running `npm run seed-data -w seeding` however the route itself is written in English so I leave that up to you to mess with :)

**Comment by vagrant-soul** [comment]
Thank you very much for receiving your documents

**Comment by vagrant-soul** [comment]
Thank you very much for receiving your documents

**Comment by vagrant-soul** [comment]
Thank you very much for your documents
