### ISSUE TITLE
The wrong direction to Kitawa in Act 5

### ISSUE THREAD

**Issue by roman-mukhlygin** [HeartofPhos/exile-leveling#92]
https://github.com/HeartofPhos/exile-leveling/blob/867f4b933262ea932a4448558483685ca382b676/common/data/routes/act-5.txt#L45C5-L45C22

> #sub Go {dir|225}

it's mistake Cathedral apex it is located diagonally from left to top about 315 degrees
![image](https://github.com/HeartofPhos/exile-leveling/assets/60079597/4f1b78ed-8e63-49ba-bb5f-9a5681bc353d)

**Comment by HeartofPhos** [comment]
This is intentional, hints are there to help you complete a given step, in this case reaching `The Cathedral Rooftop` from `The Ruined Square` which is roughly down and left from the waypoint.

While the route is consistent with this it does read counterintuitively at times, but I haven't come up with a nice way to present info at all times
